"""Manual opt-in live C06 gate, restricted to synthetic C06 smoke inputs."""

import json

from sqlalchemy import select

from app.analysis.models import GeneratedConfiguration
from app.db import SessionLocal
from app.models import SourceSpan
from app.rag.contracts import GroundedCreate
from app.rag.indexing import create_job, solver_context
from app.rag.models import RagJob
from app.rag.providers import configuration
from app.rag.workflow import execute_graph
from app.settings import get_settings


def main():
    settings = get_settings()
    if not settings.llm_api_key.get_secret_value():
        print(json.dumps({"live_gate": "unexecuted", "reason": "provider_key_missing"}))
        return
    settings = settings.model_copy(
        update={
            "rag_embedding_provider": "openai",
            "rag_embedding_model": "text-embedding-3-small",
            "rag_report_provider": "openai",
            "rag_report_model": "gpt-4.1-mini-2025-04-14",
            "rag_external_enabled": True,
        }
    )
    with SessionLocal() as db:
        candidates = db.scalars(
            select(RagJob)
            .where(RagJob.job_type == "graph", RagJob.state == "completed")
            .order_by(RagJob.created_at.desc())
        ).all()
        selected = None
        for job in candidates:
            if (
                job.config["report_provider"] != "fake"
                or job.request["body"]["question"] != "summarize"
            ):
                continue
            _, snapshot, _ = solver_context(db, job.analysis_id)
            spans = db.scalars(
                select(SourceSpan).where(
                    SourceSpan.document_version_id == snapshot["document_version_id"]
                )
            ).all()
            # This exact label is generated by the synthetic smoke, never a real tender.
            if spans and all(s.text.startswith("Synthetic C05 c06-complete.") for s in spans):
                selected = job.analysis_id
                break
        if not selected:
            print(
                json.dumps({"live_gate": "unexecuted", "reason": "synthetic_smoke_input_missing"})
            )
            return
        request = GroundedCreate(analysis_id=selected, allow_external=True)
        job, repeated = create_job(db, "graph", request, configuration(settings))
        job_id = job.id
    execute_graph(job_id, settings=settings)
    with SessionLocal() as db:
        row = db.get(RagJob, job_id)
        report = row.result
        if row.state == "completed" and report.get("status") == "feasible":
            configs = db.scalars(
                select(GeneratedConfiguration)
                .where(GeneratedConfiguration.analysis_id == selected)
                .order_by(GeneratedConfiguration.rank)
            ).all()
            assert report["configurations"] == [c.payload for c in configs]
            assert report["approval"] == "not_granted"
            assert report["sections"]
            print(
                json.dumps(
                    {
                        "live_gate": "passed",
                        "run_id": row.id,
                        "embedding_model": settings.rag_embedding_model,
                        "report_model": settings.rag_report_model,
                        "solver_unchanged": True,
                        "synthetic_only": True,
                        "idempotent": repeated,
                    }
                )
            )
        else:
            print(
                json.dumps(
                    {
                        "live_gate": "not_passed",
                        "run_id": row.id,
                        "state": row.state,
                        "error_code": row.error_code,
                        "review_blockers": report.get("review_blockers", []),
                        "synthetic_only": True,
                    }
                )
            )


if __name__ == "__main__":
    main()
